### ISSUE TITLE
Force users to register/login for buying products

### ISSUE THREAD

**Issue by parhamin2010** [parhamin2010/narmok#13]
Check woocommerce settings

**Comment by Sherwin83** [comment]
start the process

**Comment by Sherwin83** [comment]
Should i enable this?
![ggggg](https://github.com/parhamin2010/narmok/assets/131457314/4da7040f-a183-472a-a508-906e7f525189)

**Comment by Sherwin83** [comment]
its done

**Comment by Sherwin83** [comment]
It's done now, please check it
@parhamin2010
