### ISSUE TITLE
Create wallet for users

### ISSUE THREAD

**Issue by parhamin2010** [parhamin2010/narmok#14]

**Comment by Sherwin83** [comment]
![Uploading wallet.png…]()
@parhamin2010  should I add it for creating a wallet or not?

**Comment by Sherwin83** [comment]
@parhamin2010 
for crating a wallet should I add this?
![wallet](https://github.com/parhamin2010/narmok/assets/131457314/4820886a-6c98-463d-99de-9243e50c8a73)

**Comment by parhamin2010** [comment]
Please create a dev environment on your system and test it!
check this video: https://www.youtube.com/watch?v=lG7pdVmr6wo
Call me after you finish this step. after this you must clone the narmok repository on your local machine to see the website. 
After checking it on your local machine then you can install it on website.

**Comment by parhamin2010** [comment]
It's done.
