### ISSUE TITLE
Create sidebar for blog page

### ISSUE THREAD

**Issue by parhamin2010** [parhamin2010/narmok#23]
In blog pages, right side there's no sidebar and it's an empty section. add some information there that might be useful for the users like last recent posts, last recent products, best shots in home page and etc....

**Comment by Sherwin83** [comment]
![option1(product tabs)](https://github.com/parhamin2010/narmok/assets/131457314/2b1f0b84-db21-45c3-9dab-fbb8b910b69d)
![option2](https://github.com/parhamin2010/narmok/assets/131457314/d34b7107-5bda-4264-8b23-92f7b61bb9bf)
 which option is better?

also add recent blog in side bar.

**Comment by Sherwin83** [comment]
second one occupies the entire sidebar
i think the first one is better @parhamin2010

**Comment by parhamin2010** [comment]
The design of the first one is not good for showing. Found out what you can do about this. We need this section anyway but do your best regarding the design to have a qualified one. @Sherwin83

**Comment by Sherwin83** [comment]
![blog slidebar](https://github.com/parhamin2010/narmok/assets/131457314/e25cc964-9ba8-42f0-b56f-26f2c67bdf0e)
 review the blog sidebar, please.

**Comment by parhamin2010** [comment]
@Sherwin83 this is not good view. Double-check it.
![image](https://github.com/parhamin2010/narmok/assets/25672014/212eaa8d-df28-4049-904b-e5c7779791dd)

**Comment by parhamin2010** [comment]
Done
