### ISSUE TITLE
Posts inside the website has News tag!

### ISSUE THREAD

**Issue by parhamin2010** [parhamin2010/narmok#24]
Remove this tag from all posts. Post don't need news tag. remove it.

![image](https://github.com/parhamin2010/narmok/assets/25672014/136482d9-0241-482f-92e1-41131313f11c)

**Comment by Sherwin83** [comment]
![issue1](https://github.com/parhamin2010/narmok/assets/131457314/acdeafad-a137-4546-94ec-734b2ba399f9)
it's done
