### ISSUE TITLE
Replace contacts info whole over the site to proper once

### ISSUE THREAD

**Issue by parhamin2010** [parhamin2010/narmok#8]
phone: +90 535 047 1503
email: ubagodit@gmail.com 
address: Pınartepe, Avrupa Cd. No:71, 34528 Büyükçekmece/İstanbul, Türkiye

**Comment by Sherwin83** [comment]
start process...

**Comment by Sherwin83** [comment]
all of them is change except the header.
![rrrrrr](https://user-images.githubusercontent.com/131457314/235978822-19de020b-41eb-41f9-bf07-e1a702772d4b.jpg)

**Comment by parhamin2010** [comment]
@Sherwin83 please check theme configuration or header. Might be there.
