### ISSUE TITLE
add blog section to homepage

### ISSUE THREAD

**Issue by parhamin2010** [parhamin2010/narmok#9]
add blog section to home page below the products carousel

**Comment by Sherwin83** [comment]
@parhamin2010 can you explain it more?

**Comment by parhamin2010** [comment]
Below the products slider, add new section that shows us the recent blogs
![image](https://user-images.githubusercontent.com/25672014/235204274-6f22e57a-dd5f-4eaf-aaa1-bdf786fbb057.png)

**Comment by parhamin2010** [comment]
check these two pages for structure:
https://narmok.ubagod.com/home-v2/
https://narmok.ubagod.com/home-v1/

**Comment by Sherwin83** [comment]
It's almost done, for being complete we should add more blog.
please check it.
@parhamin2010
